### ISSUE TITLE
Update necessary with the change from O365 to M365

### ISSUE THREAD

**Issue by gabrieltokyo** [NetAppDocs/saasbackupO365#77] opened 2020-07-08 11:14 UTC
Page: [Signing up for a Microsoft Office 365 free trial account](https://docs.netapp.com/us-en/saasbackupO365/task_signing_up_for_o365_free_trial.html)

Could it be possible to update this page?
I do think that with the changes at Microsoft side we may need to adapt this instructions to new reality.

Regards,
Gabriel

**Comment by netapp-aherbin** [comment] 2020-07-10 20:36
Hi Gabriel,

Thank you for your feedback.  We will have an updated posted shortly.

Amanda

**Comment by netapp-rlithman** [comment] 2020-10-29 19:48
Hi Gabriel, 

The link has been updated to Microsoft 365. 

Best, 
Rachel

**Comment by netapp-rlithman** [comment] 2020-10-30 14:31
Gabriel, 

I wonder if the link update is all that you requested. When I read your comment again, I think you're asking for something else. If the issue is closed, could you close it on your end? If not, could you specify your request in updating this page? Maybe provide an example? 

Thanks again for your help in keeping our docs healthy. 

Best, 
Rachel

**Comment by gabrieltokyo** [comment] 2020-11-04 03:57
Hi Rachel, not only the link but the steps provided looks not to match current M365 Trial request method, then it would be better to review the guidance steps.
Will reach to you separately to provide more details on what I see.

**Comment by netapp-rlithman** [comment] 2020-11-04 20:00
Thank you for following up, Gabriel. I've looked into the issue using the details you sent. The process steps need an update. I've contacted the product team to confirm the new process steps. We will update the documentation as soon as possible.

**Comment by netapp-rlithman** [comment] 2020-11-09 14:56
The documentation is now updated. See the update at https://docs.netapp.com/us-en/saasbackupO365/task_signing_up_for_o365_free_trial.html.

**Closed by netapp-rlithman** 2020-11-09 14:56 UTC

**Comment by gabrieltokyo** [comment] 2020-11-12 04:19
Great work!
Thank you
