### ISSUE TITLE
Unnecessary information added in the steps 

### ISSUE THREAD

**Issue by viktorpenev** [NetAppDocs/saasbackupO365#148] opened 2022-09-14 15:35 UTC
Page: [Enable Modern Authentication](https://docs.netapp.com/us-en/saasbackupO365/task_enable_modern_authentication.html)

Hello everyone, 

Is it supposed to have the following text in the steps provided: 

Modern Authentication is now enabled.
The ZZZ config service account has been removed.

**Comment by viktorpenev** [comment] 2022-09-14 15:42
Hi Rachel,

Thank you for the prompt response.

Is it necessary to display all this text:

***@***.***

or we can just say "Accept all permissions"?

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-rlithman** [comment] 2022-09-14 15:51
The information provides the outcomes of accepting permissions. I view it as helpful. What is a disadvantage of keeping the information in the topic?

**Comment by viktorpenev** [comment] 2022-09-14 16:11
If that's actual output customer's can see, then it's my bad and it makes sense it to be there. It just looks like a random text, which was left there by mistake, but that might be just me :)

Best regards,

Viktor Penev
Technical Support Engineer
Technical Support Center

NetApp
***@***.******@***.***>

[A close up of a logo  Description automatically generated]<https://www.netapp.com/us/index.aspx>


[A close up of a sign  Description automatically generated]<https://www.facebook.com/NetApp>   [A picture containing drawing  Description automatically generated] <https://www.instagram.com/netapp/>    [A picture containing drawing, clock, sign  Description automatically generated] <https://www.youtube.com/netapp>    [A picture containing drawing  Description automatically generated] <https://www.linkedin.com/company/netapp/>    [A picture containing ax, drawing  Description automatically generated] <https://twitter.com/NetApp>

**Comment by netapp-rlithman** [comment] 2022-09-14 17:03
No problem at all, Viktor. The doc team appreciates feedback. 

I cannot verify the output on my end without the help of the product team or someone who works with the customer when they enable it. Yet, outcomes do not have to be seen in the UI as output to be explained in the documentation. It was intended to explain what happens when Modern Authentication is enabled.

**Comment by netapp-rlithman** [comment] 2022-09-21 13:37
Viktor, I'm going to close this issue. If you have any follow up questions or feedback, please let me know.

**Closed by netapp-rlithman** 2022-09-21 13:37 UTC
